on:
  push:
    branches: [master, tests]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2.1.0
        with:
          version: 0.11.0

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Zig build test Debug
        run: |
          zig build test

      - name: Zig build test Release
        run: |
          zig build test -Drelease

      # - name: Zig build cross
      #   run: |
      #     zig env
      #     zig build cross -Drelease

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: bin
      #     path: zig-out/bin/*
